name: dart_pre_commit
description: A small collection of pre commit hooks to format and lint dart code
version: 5.4.3
homepage: https://github.com/Skycoder42/dart_pre_commit

environment:
  sdk: ^3.7.0

platforms:
  linux:
  macos:
  windows:

executables:
  dart_pre_commit: dart_pre_commit

dependencies:
  analyzer: ^7.3.0
  args: ^2.6.0
  checked_yaml: ^2.0.3
  console: ^4.1.0
  convert: ^3.1.2
  crypto: ^3.0.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  path: ^1.9.1
  pub_semver: ^2.1.5
  pubspec_parse: ^1.5.0
  riverpod: ^2.6.1
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  coverage: ^1.11.1
  custom_lint: ^0.7.3
  dart_test_tools: ^6.0.3
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  test: ^1.25.15
  yaml_edit: ^2.2.2

cider:
  link_template:
    tag: https://github.com/Skycoder42/dart_pre_commit/releases/tag/v%tag%
    diff: https://github.com/Skycoder42/dart_pre_commit/compare/v%from%...v%to%

dart_pre_commit:
  pull-up-dependencies:
    allowed:
      - analyzer
      - meta
      - path
