name: dart_pre_commit
description: A small collection of pre commit hooks to format and lint dart code
version: 5.3.1
homepage: https://github.com/Skycoder42/dart_pre_commit

environment:
  sdk: ^3.5.0

platforms:
  linux:
  macos:
  windows:

executables:
  dart_pre_commit: dart_pre_commit

dependencies:
  analyzer: ^6.7.0
  args: ^2.5.0
  checked_yaml: ^2.0.3
  console: ^4.1.0
  convert: ^3.1.1
  crypto: ^3.0.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logging: ^1.2.0
  meta: ^1.15.0
  path: ^1.9.0
  pub_semver: ^2.1.4
  pubspec_parse: ^1.3.0
  riverpod: ^2.5.1
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.12
  coverage: ^1.9.2
  custom_lint: ^0.6.7
  dart_test_tools: ^6.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.8
  yaml_edit: ^2.2.1

cider:
  link_template:
    tag: https://github.com/Skycoder42/dart_pre_commit/releases/tag/v%tag%
    diff: https://github.com/Skycoder42/dart_pre_commit/compare/v%from%...v%to%

dart_pre_commit:
  pull-up-dependencies:
    allowed:
      - analyzer
      - meta
      - test
